package main

import (
	"go/ast"
	"go/parser"
	"go/token"
	"math"
	"os"
	"path/filepath"
	"testing"
)

func TestCyclomaticComplexity(t *testing.T) {
	source := `package sample
func risk(a, b bool, xs []int, value any) int {
	if a && b { return 1 }
	for range xs { break }
	switch value {
	case 1: return 2
	case 2: return 3
	default: return 4
	}
}
`
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "sample.go", source, 0)
	if err != nil {
		t.Fatal(err)
	}
	fn := file.Decls[0].(*ast.FuncDecl)
	if got, want := cyclomaticComplexity(fn.Body), 6; got != want {
		t.Fatalf("cyclomaticComplexity() = %d, want %d", got, want)
	}
}

func TestCyclomaticComplexityExcludesNestedFunction(t *testing.T) {
	source := `package sample
func outer() {
	f := func(a bool) { if a {} }
	_ = f
}
`
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "sample.go", source, 0)
	if err != nil {
		t.Fatal(err)
	}
	fn := file.Decls[0].(*ast.FuncDecl)
	if got := cyclomaticComplexity(fn.Body); got != 1 {
		t.Fatalf("cyclomaticComplexity() = %d, want 1", got)
	}
}

func TestDiscoverAndScoreFunction(t *testing.T) {
	repo := t.TempDir()
	path := filepath.Join(repo, "risk.go")
	source := `package sample

func risk(x int) int {
	if x > 0 {
		return 1
	}
	return 0
}
`
	if err := os.WriteFile(path, []byte(source), 0o600); err != nil {
		t.Fatal(err)
	}
	functions, skipped, err := discoverFunctions(repo, changeSet{"risk.go": {{Start: 4, End: 5}}}, false, false)
	if err != nil {
		t.Fatal(err)
	}
	if len(skipped) != 0 || len(functions) != 1 {
		t.Fatalf("discoverFunctions() = %d functions, skipped %v", len(functions), skipped)
	}
	profile := &coverageProfile{
		Format:           "go",
		CanCompareCounts: true,
		Files: map[string][]coverageBlock{"risk.go": {
			{Start: sourcePosition{Line: 4, Column: 2}, End: sourcePosition{Line: 4, Column: 10}, Statements: 1, Count: 1},
			{Start: sourcePosition{Line: 5, Column: 3}, End: sourcePosition{Line: 5, Column: 11}, Statements: 1, Count: 1},
			{Start: sourcePosition{Line: 7, Column: 2}, End: sourcePosition{Line: 7, Column: 10}, Statements: 1, Count: 0},
		}},
		Branches: map[string][]explicitBranch{},
	}
	results := scoreFunctions(functions, profile, 30)
	if len(results) != 1 {
		t.Fatalf("scoreFunctions() returned %d results", len(results))
	}
	result := results[0]
	if result.Complexity != 2 || math.Abs(result.Coverage-2.0/3.0) > 0.0001 {
		t.Fatalf("unexpected result: %#v", result)
	}
	if result.CoveredBranches != 1 || result.UnknownBranches != 0 || result.UncoveredBranches != 1 {
		t.Fatalf("unexpected branches: %#v", result.Branches)
	}
}

func TestGeneratedFileIsSkipped(t *testing.T) {
	repo := t.TempDir()
	source := "// Code generated by a test. DO NOT EDIT.\npackage sample\nfunc generated() {}\n"
	if err := os.WriteFile(filepath.Join(repo, "generated.go"), []byte(source), 0o600); err != nil {
		t.Fatal(err)
	}
	functions, skipped, err := discoverFunctions(repo, changeSet{"generated.go": {{Start: 1, End: 3}}}, false, false)
	if err != nil {
		t.Fatal(err)
	}
	if len(functions) != 0 || len(skipped) != 1 {
		t.Fatalf("got %d functions and skipped %v", len(functions), skipped)
	}
}
